Repository wissamfa/SOEN341_Project, pull requests merged in 2020-02, with the labels that each got.

#16 #5 creating the base of the User class
  SOEN/userclass.js
Labels: enhancement

#28 #26, #27 - Added login and logout functionality
  SOEN/src/app/login/login.component.ts
Labels: backend

#29 #19 #20 - Regulating path from firebase
  SOEN/src/app/shared/services/auth.service.ts
Labels: bug, enhancement

#31 #25-added the register functionality
  SOEN/src/app/register/register.component.ts
Labels: backend, enhancement

#30 #19 - Gets user info for user's profile page
  SOEN/src/app/profile/user-info/user-info.component.ts
Labels: backend, enhancement
