Repository wissamfa/SOEN341_Project, pull requests merged in 2020-04, with the labels that each got.

#59 #52 #5 the user profile page styling is provided
  SOEN/style/user_profile_style.css
Labels: frontend

#60 #47 front end style for the mypost page
  SOEN/style/style.css
Labels: frontend

#63 #20 Creating fromend page for forget password
  SOEN/EndUser PHP Files/forgot_password.php
Labels: frontend

#64 #58 Creating a Navbar on the toop of the application
  SOEN/includes/header.php
Labels: frontend

#65 #33 Creating a home page
  SOEN/EndUser PHP Files/home.php
Labels: frontend

#66 #57 application members search features
  SOEN/EndUser PHP Files/members.php
Labels: frontend

#67 #47 Creating a mypost page to view the users posts
  SOEN/EndUser PHP Files/my_post.php
Labels: frontend

#82 #5, #52 - Added the user profile page
  SOEN/EndUser PHP Files/user_profile.php
Labels: backend, frontend

#81 #35 - added the messages feature
  SOEN/EndUser PHP Files/messages.php
Labels: backend

#80 #46 - created the main page
  SOEN/EndUser PHP Files/main.php
Labels: backend, frontend

#79 #4,#40 - added the insert post function
  SOEN/functions/functions.php
Labels: backend

#83 #4, #40 - function to get posts from database
  SOEN/functions/functions.php
Labels: backend

#84 #50 - functionality for the single post
  SOEN/functions/functions.php
Labels: backend

#85 #48 - added user posts functionality
  SOEN/functions/functions.php
Labels: backend

#86 #54 - added the search bar functionality
  SOEN/functions/functions.php
Labels: backend

#87 #54 - added the results function
  SOEN/functions/functions.php
Labels: backend

#88 #38 Added the functionality to insert a user
  SOEN/EndUser PHP Files/insert_user.php
Labels: backend

#89 #51 Added tooltip function
  SOEN/EndUser PHP Files/jquery.js
Labels: backend

#90 #27 Added logout function
  SOEN/EndUser PHP Files/logout.php
Labels: backend

#91 #43 Added pagination for mypost page
  SOEN/functions/pagination_mypost.php
Labels: backend

#92 #44 Added pagination for user profile
  SOEN/functions/pagination_user_profile.php
Labels: backend

#93 #25 Added signup page
  SOEN/EndUser PHP Files/signup.php
Labels: frontend

#94 #49 Added view button page
  SOEN/EndUser PHP Files/single.php
Labels: frontend

#95 #6 Added comments function
  SOEN/functions/comments.php
Labels: backend, user story

#96 #33 Added index function
  SOEN/EndUser PHP Files/index.php
Labels: backend

#78 #20-added the design for the sign in page
  SOEN/EndUser PHP Files/signin.php
Labels: frontend

#77 #53-added the functionality for the search bar
  SOEN/EndUser PHP Files/results.php
Labels: backend

#76 #10-added the profile page code
  SOEN/EndUser PHP Files/profile.php
Labels: backend, frontend

#75 #41-added the pagination for the profile
  SOEN/functions/pagination_profile.php
Labels: backend

#74 #42-added the pagination for the home page
  SOEN/functions/pagination_home.php
Labels: backend

#73 #37-created the functionality for the login button
  SOEN/EndUser PHP Files/login.php
Labels: backend

#72 #56-created the edit profile page
  SOEN/EndUser PHP Files/edit_profile.php
Labels: backend, frontend, user story

#71 #55-created the edit post button
  SOEN/EndUser PHP Files/edit_post.php
Labels: backend, frontend

#70 #4-added the delete button functionality
  SOEN/functions/delete_post.php
Labels: backend

#69 #45-added connection to the database
  SOEN/includes/connection.php
Labels: backend

#68 #39-added functionality for forget password page
  SOEN/EndUser PHP Files/change_password.php
Labels: backend

#98 #97 allowing travis ci to access the php codes
  SOEN/.travis.yml
Labels: testing

#100 The Gram Architecture
  Untitled Diagram-3.jpg
Labels: backend, frontend

#101 TheGram Architecture
  TheGram Arch.jpg
Labels: backend, frontend
